### PR TITLE
store/cache: produce CommitKVStore benchmark

### PR DESCRIPTION
**Pull request by odeke-em**
## Description

closes: #XXXX

---

Before we can merge this PR, please make sure that all the following items have been
checked off. If any of the checklist items are not applicable, please leave them but
write a little note why.

- [ ] Targeted PR against correct branch (see [CONTRIBUTING.md](https://github.com/cosmos/cosmos-sdk/blob/master/CONTRIBUTING.md#pr-targeting))
- [ ] Linked to Github issue with discussion and accepted design OR link to spec that describes this work.
- [ ] Code follows the [module structure standards](https://github.com/cosmos/cosmos-sdk/blob/master/docs/building-modules/structure.md).
- [ ] Wrote unit and integration [tests](https://github.com/cosmos/cosmos-sdk/blob/master/CONTRIBUTING.md#testing)
- [ ] Updated relevant documentation (`docs/`) or specification (`x/<module>/spec/`)
- [ ] Added relevant `godoc` [comments](https://blog.golang.org/godoc-documenting-go-code).
- [ ] Added a relevant changelog entry to the `Unreleased` section in `CHANGELOG.md`
- [ ] Re-reviewed `Files changed` in the Github PR explorer
- [ ] Review `Codecov Report` in the comment section below once CI passes

### CODE REVIEW

**Comment by odeke-em** [comment]
@cuonglm why is this branch being used to push to master? I see this
F1EE4718-89CA-4A97-9B1A-4687C31E8AFC

did you mean to push to this branch and trigger builds here or what?

**Comment by cuonglm** [comment]
Not sure, I just want to trigger a build for master, then trigger another build from other branch. So we have 2 build with -count=10 to compare

**Comment by cuonglm** [comment]
> Not sure, I just want to trigger a build for master, then trigger another build from other branch. So we have 2 build with -count=10 to compare

To clarify, I just do push force on master branch in my local.

**Comment by odeke-em** [comment]
Good to hear that master successfully built, now we need to know how long it took, how stable are the results, could we please get this PR building with the bot’s normal flow by pushing to this change so that we can get conclusive results about the time and noise reductions.

**Comment by cuonglm** [comment]
I have one https://github.com/orijtech/cosmos-sdk/pull/11

**Pull request closed without merging**
